#!/usr/bin/env bash
readonly NVIM_PATH="${HOME}/.config/nvim"
readonly PLUGIN_PATH="${NVIM_PATH}/after/ftplugin"
readonly FT_PLUGINS=( "resources/text.vim" "resources/python.vim" "resources/markdown.vim" "resources/snakemake.vim")

readonly CONFIG_PATH="${HOME}/.config"
readonly LINTER_CONFIGS=( "resources/python/flake8" "resources/python/pylintrc" )


install_ftplugins() {
    printf "Creating symlinks in ${PLUGIN_PATH} to the to filetype plugins.\n"
    for plugin in "${FT_PLUGINS[@]}"; do
        printf " - Creating a symlink to ${plugin}... "
        ln --force --symbolic --target-directory="${PLUGIN_PATH}" "${PWD}/${plugin}" \
            || exit 1 && echo "OK"
    done
}

install_linter_configs() {
    printf "Creating symlinks in ${CONFIG_PATH} to the to the linter configs.\n"
    for config in "${LINTER_CONFIGS[@]}"; do
        printf " - Creating a symlink to ${config}... "
        ln --force --symbolic --target-directory="${CONFIG_PATH}" "${PWD}/${config}" \
            || exit 1 && echo "OK"
    done
}


main() {
    install_ftplugins
    install_linter_configs
}
main
