#!/usr/bin/env python3
"""
Wraps a specified cpp linter to refer to the source file or test file if
either are present.
"""
import sys
import subprocess
import os.path

def main(linter: str, *args):
    """Wrap the provided linter."""
    filename = args[-1]
    (root, extension) = os.path.splitext(filename);
    if extension in ['.h', '.hpp']:
        source_file = root + '.cpp'
        test_file = root + '_test.cpp'
        if os.path.isfile(source_file):
            filename = source_file
        elif os.path.isfile(test_file):
            filename = test_file
        else:
            pass  # Filename unchanged

    return subprocess.run([linter] + list(args[:-1]) + [filename])


if __name__ == '__main__':
    main(sys.argv[1], *sys.argv[2:]);
